version: "3"
services:
  studentfrontend:
    image: student-frontend
    ports:
      - 7000:80
  studentbackend:
    image: student-backend
    ports:
      - 5001:5001
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - mongo_db_data:/Users/mohantella/Documents/data/db

volumes:
  mongo_db_data:
